#!/bin/sh

# Update the include paths for the moved files in Casacore release 2.0.

# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

for FILE in $(find ./ -type f \( -name '*.c' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' -o -name '*.cc' -o -name '*.hh' -o -name '*.C' -o -name '*.H' -o -name '*.py' \) -a \( ! -name './.git' -a ! -name './.svn' -a ! -name './.subversion' -a ! -name './' \) -printf "%p ")
do
    sed -i -f $pgmpath/taql.sed "$FILE"
    sed -i -f $pgmpath/dataman.sed "$FILE"
    sed -i -f $pgmpath/latticemath.sed "$FILE"
    sed -i -f $pgmpath/lel.sed "$FILE"
    sed -i -f $pgmpath/regions.sed "$FILE"
    sed -i -f $pgmpath/mssel.sed "$FILE"
    sed -i -f $pgmpath/msoper.sed "$FILE"
done
