#!/bin/sh

# Add casacore/ to the #include path for Casacore release 2.0.

for FILE in $(find ./ -type f \( -name '*.c' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' -o -name '*.cc' -o -name '*.hh' -o -name '*.C' -o -name '*.H' -o -name '*.py' \) -a \( ! -name './.git' -a ! -name './.svn' -a ! -name './.subversion' -a ! -name './' \) -printf "%p ")
do
  perl -p -i -e s'%(#\s*include\s*<\s*)(casa|tables|scimath|measures|lattices|images|ms|msfits|meas|derivedmscal|coordinates|mirlib|fits|python/Converters)/%\1casacore/\2/%' "$FILE"
done
